// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewAuthor struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}

type NewBook struct {
	Name     string `json:"name"`
	Category string `json:"category"`
}
